# Generated by Django 3.0.8 on 2021-01-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.IntegerField()),
                ('leader_name', models.TextField()),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_phone_number', models.IntegerField()),
                ('team_name', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
