# Generated by Django 3.0.8 on 2021-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_type',
            field=models.TextField(null=True),
        ),
    ]
