# Generated by Django 3.0.8 on 2021-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210115_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamID',
            field=models.BigIntegerField(),
        ),
    ]
