# Generated by Django 3.0.8 on 2021-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210124_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='leader_phone_number',
            field=models.TextField(),
        ),
    ]
