# Generated by Django 3.0.8 on 2021-01-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210125_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
